name: pytorch
channels:
- https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/
dependencies:
- python=3.10
- numpy
- pandas
- xarray
- botocore
- boto3
- scikit-learn
- scipy
- pip
- pip:
  - onnx
  - onnxruntime-gpu==1.9
  - onnxsim
  - polygraphy
  - torch==1.12.1
  - torchvision==0.13.1
  - trtpy